import { invitationCopyDefaults, parseEditableCopy, parseEnglishEditableCopy, type EditableInvitationCopy } from "@/lib/templates/editable-copy";
import { invitationTitleCase, weddingParentLine, type WeddingChildKind } from "@/lib/events/parents";

export type InvitationLanguage = "ID" | "EN";

/** Text owned by the invitation product. Event data and customer-authored copy are never machine-translated. */
const english: Record<string, string> = {
  "Di antara doa dan rasa syukur, kami mengundang Anda untuk merayakan khitanan putra kami.": "With prayers and gratitude, we invite you to celebrate our son's khitan with us.",
  "Mari hadir dan berbagi hari yang hangat bersama keluarga kami.": "Join our family for a warm day together.",
  "Semoga langkah kecilnya selalu dipenuhi kesehatan, kebaikan, dan kasih sayang.": "May his little steps be filled with health, kindness and love.",
  "Terima kasih telah mengiringi hari ini dengan kehadiran dan doa yang baik.": "Thank you for sharing this day with your presence and kind prayers.",
  "Dengan rasa syukur, keluarga kami membuka pintu untuk berbagi kebahagiaan pada syukuran khitanan putra kami.": "With gratitude, our family welcomes you to share the joy of our son's khitan celebration.",
  "Luangkan waktu untuk berkumpul, berbagi cerita, dan mendoakan putra kami.": "Come together, share stories and offer your prayers for our son.",
  "Semoga ia tumbuh menjadi anak yang sehat, santun, dan membawa kebaikan bagi sesama.": "May he grow up healthy, thoughtful and kind to others.",
  "Kehadiran Anda membuat rumah dan hati kami semakin hangat. Terima kasih atas doanya.": "Your presence warms our home and our hearts. Thank you for your prayers.",
  "Ada langkah baru dalam cerita si kecil. Dengan bahagia, kami mengundang Anda ke syukuran khitanannya.": "A new step in our little one's story. We joyfully invite you to his khitan celebration.",
  "Yuk, hadir untuk berbagi tawa, kebersamaan, dan doa yang baik bersama kami.": "Join us for laughter, togetherness and kind wishes.",
  "Semoga rasa ingin tahunya tumbuh bersama hati yang baik dan tubuh yang sehat.": "May his curiosity grow alongside a kind heart and good health.",
  "Terima kasih sudah ikut merayakan satu langkah kecil yang begitu berarti bagi keluarga kami.": "Thank you for celebrating a little step that means so much to our family.",
  "Kami mengundang Anda untuk berbagi rasa syukur dan doa pada khitanan putra kami.": "We invite you to share our gratitude and prayers at our son's khitan celebration.",
  "Kehadiran Anda akan menjadi bagian berharga dari hari yang kami nantikan.": "Your presence will be a treasured part of the day we look forward to.",
  "Semoga hidupnya selalu diterangi kebaikan, kesehatan, dan doa orang-orang tersayang.": "May kindness, health and the prayers of loved ones light his life.",
  "Terima kasih untuk setiap doa yang mengiringi langkahnya. Kami menantikan kebersamaan dengan Anda.": "Thank you for every prayer accompanying his journey. We look forward to being together.",
  "Dengan penuh rasa syukur, kami mengundang Anda untuk menyaksikan pertemuan kedua keluarga dalam acara sangjit kami.": "With gratitude, we invite you to join both families at our sangjit celebration.",
  "Mari berbagi kebahagiaan dan menjadi bagian dari hari yang berarti bagi kedua keluarga.": "Share our joy on a day that means so much to both families.",
  "Semoga ikatan ini tumbuh dalam keharmonisan, saling menghormati, dan kasih yang hangat.": "May this bond grow in harmony, mutual respect and warm affection.",
  "Terima kasih telah menyertai pertemuan ini dengan kehadiran dan harapan baik Anda.": "Thank you for sharing this gathering with your presence and kind wishes.",
  "Dengan hangat, kami mengundang Anda untuk merayakan ikatan kedua keluarga pada acara sangjit kami.": "We warmly invite you to celebrate the bond between our families at our sangjit.",
  "Kehadiran Anda akan melengkapi hari yang kami susun dengan kasih dan rasa syukur.": "Your presence will complete a day prepared with love and gratitude.",
  "Semoga kebersamaan ini selalu dipenuhi kelembutan, pengertian, dan kasih yang terus tumbuh.": "May our togetherness be filled with tenderness, understanding and a growing love.",
  "Terima kasih telah berbagi kebahagiaan bersama kedua keluarga kami. Sampai bertemu.": "Thank you for sharing the happiness of both our families. We look forward to seeing you.",
  "Dua keluarga berkumpul untuk merayakan sebuah ikatan. Dengan hormat, kami mengundang Anda ke acara sangjit kami.": "Two families gather to celebrate a bond. We respectfully invite you to our sangjit celebration.",
  "Mari hadir dan berbagi hari penuh makna bersama kedua keluarga kami.": "Join both our families for a meaningful day together.",
  "Semoga ikatan yang dirayakan membawa kebahagiaan, keharmonisan, dan rasa saling menjaga.": "May the bond we celebrate bring happiness, harmony and care for one another.",
  "Terima kasih atas kehadiran dan doa baik Anda untuk kedua keluarga kami.": "Thank you for your presence and kind wishes for both our families.",
  "Kami mengundang Anda untuk menjadi bagian dari pertemuan kedua keluarga pada hari sangjit kami.": "We invite you to be part of our families' gathering on our sangjit day.",
  "Kehadiran Anda akan menambah hangat cerita yang kami rayakan bersama keluarga.": "Your presence will bring warmth to the story we celebrate with our families.",
  "Semoga setiap langkah bersama selalu membawa pengertian, ketenangan, dan kasih.": "May every step together bring understanding, peace and love.",
  "Terima kasih sudah menyertai hari ini dengan kehadiran dan harapan baik. Sampai bertemu bersama keluarga kami.": "Thank you for sharing this day with your presence and kind wishes. We look forward to welcoming you.",
  "Khitanan": "Khitan Celebration",
  "Syukuran Khitanan": "Khitan Celebration",
  "Syukur untuk langkah kecilnya": "Gratitude for his next little step",
  "Sebuah ikatan, dua keluarga": "One bond, two families",
  "Dengan penuh rasa syukur, kami mengundang Anda untuk hadir pada syukuran khitanan putra kami.": "With gratitude, we invite you to celebrate our son's khitan with us.",
  "Mari berbagi kebahagiaan dan doa bersama keluarga kami. Kehadiran Anda akan membuat hari ini semakin berarti.": "Join our family in sharing joy and prayers. Your presence will make this day even more meaningful.",
  "Semoga putra kami tumbuh sehat, berhati baik, dan selalu dikelilingi kasih serta doa yang baik.": "May our son grow in good health and kindness, always surrounded by love and warm wishes.",
  "Terima kasih atas kehadiran dan doa Anda. Semoga kebersamaan ini menjadi kenangan yang hangat bagi kita semua.": "Thank you for your presence and prayers. May this time together become a warm memory for us all.",
  "Dua keluarga bertemu untuk merangkai ikatan yang penuh makna. Dengan hangat, kami mengundang Anda ke acara sangjit kami.": "Two families come together to form a meaningful bond. We warmly invite you to our sangjit celebration.",
  "Kehadiran Anda akan melengkapi kebahagiaan kedua keluarga pada hari istimewa ini.": "Your presence will complete both families' joy on this special day.",
  "Semoga ikatan ini membawa kasih, keharmonisan, dan kebersamaan yang terus bertumbuh.": "May this bond bring love, harmony and togetherness that keep growing.",
  "Terima kasih telah menjadi bagian dari pertemuan kedua keluarga kami. Sampai bertemu di hari yang penuh kebahagiaan.": "Thank you for being part of our families' gathering. We look forward to seeing you on this joyful day.",
  "Kami sedang menanti cerita kecil yang akan membawa banyak bahagia. Kami ingin berbagi rasa syukur ini bersama Anda.": "We are waiting for a little story that will bring so much joy. We would love to share this grateful moment with you.",
  "Datanglah untuk berbagi doa, cerita, dan kebersamaan sebelum kami menyambut si kecil.": "Join us for good wishes, stories and togetherness as we prepare to welcome our little one.",
  "Semoga si kecil dan keluarga selalu dikelilingi kesehatan, kasih, dan hari-hari yang hangat.": "May our little one and family be surrounded by health, love and warm days.",
  "Terima kasih telah ikut menantikan kebahagiaan kecil ini bersama kami. Kehadiran dan harapan baik Anda sangat berarti.": "Thank you for sharing in the joy of this little arrival. Your presence and kind wishes mean so much.",
  "Ada pertemuan yang ingin kami isi dengan cerita, tawa, dan kebersamaan. Anda diundang untuk menjadi bagiannya.": "There is a gathering we would love to fill with stories, laughter and togetherness. You are invited to be part of it.",
  "Luangkan waktu untuk hadir dan menikmati momen ini bersama kami. Kami menantikan kehadiran Anda.": "Make time to join us and enjoy this moment together. We look forward to seeing you.",
  "Semoga pertemuan ini membawa kenangan baik dan kebersamaan yang terus terjaga.": "May this gathering bring good memories and lasting connections.",
  "Terima kasih telah membuka ruang untuk bertemu dan berbagi. Sampai jumpa di acara!": "Thank you for making time to meet and share. See you at the event!",
  "Kami ingin merayakan perjalanan yang telah kami jalani bersama, dengan orang-orang yang membuatnya begitu berarti.": "We would love to celebrate our journey together with the people who have made it so meaningful.",
  "Mari hadir dan berbagi cerita pada perayaan hari jadi pernikahan kami. Kehadiran Anda akan melengkapi kebahagiaan ini.": "Please join us to share stories and celebrate our wedding anniversary. Your presence will make this day complete.",
  "Semoga hari-hari berikutnya selalu membawa kesehatan, ketenangan, dan kasih yang terus tumbuh.": "May the days ahead bring health, peace and a love that keeps growing.",
  "Terima kasih telah menemani perjalanan ini dengan doa dan kebersamaan. Sampai bertemu di hari perayaan.": "Thank you for being part of our journey with your kindness and good wishes. See you at the celebration.",
  "Ada banyak kenangan yang kami simpan, dan satu hari istimewa yang ingin kami rayakan bersama Anda.": "We hold so many memories close, and there is one special day we would love to celebrate with you.",
  "Dengan penuh syukur kami mengundang Anda untuk berkumpul dan merayakan hari jadi pernikahan kami.": "With gratitude, we invite you to gather with us and celebrate our wedding anniversary.",
  "Semoga keluarga kita selalu dikelilingi kasih, kesehatan, dan kebersamaan yang hangat.": "May our family always be surrounded by love, good health and warm togetherness.",
  "Waktu menjadi lebih berharga ketika dibagi dengan orang-orang tersayang. Terima kasih telah menjadi bagian dari cerita kami.": "Time becomes more precious when shared with those we love. Thank you for being part of our story.",
  "Gulir untuk membaca": "Scroll to read",
  "Ulang Tahun": "Birthday",
  "Mode desain": "Design mode",
  "Ada pesta untukmu": "You are invited",
  "Rayakan": "Celebrate",
  "Gulir untuk merayakan": "Scroll to celebrate",
  "Datang dan rayakan": "Come celebrate",
  "Yang berulang tahun": "The birthday star",
  "Rencana pesta": "The party plan",
  "Simpan tanggalnya": "Save the date",
  "Potongan bahagia": "Happy memories",
  "Sebentar lagi": "Almost time",
  "Tempat kita bertemu": "Meet us here",
  "Datang, ya?": "Coming along?",
  "Titipkan ucapan": "Leave a wish",
  "Tanda kasih": "A little gift",
  "Sampai di pesta!": "See you at the party!",
  "Pilih foto": "Choose a photo",
  "Ada satu hari yang ingin kami rayakan bersama orang-orang tersayang. Kamu diundang!": "There is a special day we want to celebrate with our favourite people. You are invited!",
  "Yuk, datang dan ikut merayakan. Kehadiranmu akan membuat hari ini semakin hangat.": "Come along and celebrate. Your presence will make this day even brighter.",
  "Semoga tahun yang baru dipenuhi kesehatan, kebahagiaan, dan banyak hal baik.": "May the year ahead bring health, happiness, and many good things.",
  "Terima kasih untuk doa dan kebersamaannya. Sampai bertemu di pesta!": "Thank you for your kind wishes and company. See you at the party!",
  "Sebuah Undangan Untuk Anda": "An Invitation For You",
  "A story in paper": "A story in paper",
  "Selembar kecil untuk satu hari yang besar.": "A little page for one very big day.",
  "Kolase Kertas": "Paper Keepsakes",
  "Selembar Cerita": "A Page of Story",
  "Catatan Kecil": "A Little Note",
  "Ruang untuk Tumbuh": "Room to Grow",
  "Setiap perayaan dimulai dari hal kecil yang ingin disimpan lebih lama.": "Every celebration begins with small things we want to keep a little longer.",
  "Nama, doa, dan waktu berkumpul seperti potongan kertas yang akhirnya menemukan tempat.": "Names, wishes, and moments gather like paper pieces finally finding their place.",
  "Yang kami rayakan bukan kesempurnaan, melainkan cerita yang terus bertumbuh.": "What we celebrate is not perfection, but a story that keeps growing.",
  "Selembar demi selembar, kami merangkai undangan ini untuk berbagi satu hari yang begitu berarti bagi kami.": "Page by page, we made this invitation to share a day that means so much to us.",
  "Kehadiran Anda akan menjadi bagian hangat dari cerita yang sedang kami susun bersama.": "Your presence will be a warm part of the story we are putting together.",
  "Semoga langkah yang kami mulai selalu punya ruang untuk tumbuh, menguat, dan saling menjaga.": "May the path we begin always have room to grow, become stronger, and care for one another.",
  "Terima kasih telah membuka lembar ini, mendoakan, dan menjadi bagian dari hari yang ingin kami simpan lama.": "Thank you for opening this page, for your wishes, and for being part of a day we hope to keep close for a long time.",
  "Kami Mengundang Anda": "You Are Invited",
  "Sebuah perayaan yang abadi": "A Timeless Celebration",
  "Undangan malam untuk Anda": "An Evening Invitation For You",
  "Admit one unforgettable evening": "Admit one unforgettable evening",
  "A gilded soirée": "A gilded soirée",
  "Kilau boleh berlalu; cerita ini tidak.": "The sparkle may fade; this story will not.",
  "Vignette Malam": "Evening Vignettes",
  "Sebuah Kilau": "A Glimmer",
  "Sebuah Irama": "A Rhythm",
  "Sebuah Pantulan": "A Reflection",
  "Cahaya keemasan menjadi aksen, sementara cerita tetap menjadi pusat malam.": "Golden light becomes the accent, while the story remains the heart of the evening.",
  "Ritme, tawa, dan jeda kecil membentuk suasana yang ingin dikenang.": "Rhythm, laughter, and quiet pauses shape an evening worth remembering.",
  "Yang paling berharga bukan dekorasinya, melainkan siapa yang hadir di dalam cerita.": "The most precious part is not the décor, but who is present in the story.",
  "Dengan hangat kami mengundang Anda ke sebuah malam yang dirangkai dalam cahaya, irama, dan kebersamaan.": "With warm hearts, we invite you to an evening composed of light, rhythm, and togetherness.",
  "Kehadiran Anda akan menjadi bagian paling berharga dari perayaan yang ingin kami kenang.": "Your presence will be the most treasured part of the celebration we hope to remember.",
  "Semoga langkah baru ini tetap berkilau oleh kasih, ketenangan, dan keberanian untuk terus memilih satu sama lain.": "May this new chapter keep shining with love, calm, and the courage to keep choosing one another.",
  "Terima kasih telah hadir dan menjadi bagian dari satu malam yang akan tinggal lebih lama daripada gemerlapnya.": "Thank you for being present and becoming part of an evening that will remain long after the sparkle fades.",

  "Kisah yang lembut, janji yang tinggal lebih lama dari waktu.": "A gentle story, a promise that outlives time.",
  "Galeri Kenangan": "Keepsake Gallery",
  "Sebuah Janji": "A Promise",
  "Sebuah Kenangan": "A Keepsake",
  "Sebuah Perjalanan": "A Journey",
  "Yang tetap tinggal": "What Remains",
  "Yang ingin dikenang": "What We Remember",
  "Yang tumbuh bersama": "What Grows Together",
  "Bukan hanya tentang satu hari, tetapi tentang pilihan untuk terus berjalan bersama.": "Not only about one day, but the choice to keep walking together.",
  "Ada detail kecil yang suatu hari akan membawa kita kembali pada rasa hari ini.": "Small details can one day carry us back to how this day felt.",
  "Dua cerita tidak harus sama untuk dapat saling mencerminkan dan saling menjaga.": "Two stories do not need to be the same to reflect and care for one another.",
  "Dengan penuh syukur, kami mengundang Anda untuk hadir pada sebuah hari yang ingin kami kenang dengan hangat dan penuh makna.": "With heartfelt gratitude, we invite you to a day we hope to remember with warmth and meaning.",
  "Kehadiran Anda akan menjadi bagian berharga dari perayaan yang kami simpan dekat di hati.": "Your presence will be a treasured part of the celebration we hold close to our hearts.",
  "Semoga langkah yang kami mulai bersama selalu dipenuhi kasih, keteguhan, dan kebaikan yang bertahan lama.": "May the path we begin together be filled with love, steadfastness, and lasting kindness.",
  "Terima kasih atas doa, waktu, dan kehadiran yang menjadikan hari ini semakin berarti bagi kami. Sampai bertemu.": "Thank you for your wishes, your time, and your presence, which make this day even more meaningful to us. We look forward to seeing you.",
  "Setelah cahaya terakhir": "After the Last Light",
  "Malam menyimpan cahaya yang hanya kita berdua mengerti.": "The night holds a light only the two of us understand.",
  "Beberapa malam terlalu indah untuk dibiarkan berlalu tanpa dikenang.": "Some nights are too beautiful to pass without being remembered.",
  "Saat malam turun dan cahaya menjadi lebih pelan, kami mengundang Anda untuk hadir di satu perayaan yang kami simpan dekat di hati.": "As night falls and the light grows softer, we invite you to a celebration we hold close to our hearts.",
  "Kehadiran Anda akan menjadi bagian hangat dari malam yang ingin kami kenang selamanya.": "Your presence will be a warm part of the night we hope to remember forever.",
  "Semoga perjalanan baru ini selalu menemukan cahaya, bahkan pada malam yang paling sunyi.": "May this new journey always find light, even on the quietest nights.",
  "Terima kasih telah hadir, mendoakan, dan tinggal sejenak bersama kami di malam yang berarti ini. Sampai bertemu.": "Thank you for being present, for your wishes, and for sharing this meaningful night with us. We look forward to seeing you.",
  "Senja di taman": "An Evening in the Garden",
  "Di bawah cahaya hangat, sebuah hari baru akan dimulai.": "Beneath the warm lights, a new chapter is about to begin.",
  "Cahaya kecil, tawa panjang, dan kenangan yang ingin kami simpan.": "Small lights, long laughter, and memories we want to keep.",
  "Menjelang senja, di antara cahaya kecil dan udara taman, kami mengundang Anda untuk hadir di hari yang kami nantikan.": "As twilight approaches, among small lights and garden air, we invite you to share the day we have been waiting for.",
  "Kehadiran Anda akan membuat taman ini terasa lebih hangat dan cerita hari itu menjadi lebih lengkap.": "Your presence will make the garden feel warmer and the story of the day more complete.",
  "Semoga langkah baru ini selalu menemukan cahaya, keteduhan, dan ruang untuk tumbuh bersama.": "May this new chapter always find light, shelter, and room to grow together.",
  "Terima kasih telah datang, mendoakan, dan berbagi cahaya pada hari yang begitu berarti bagi kami. Sampai bertemu di taman.": "Thank you for coming, for your wishes, and for sharing your light on a day that means so much to us. We look forward to seeing you in the garden.",
  "Sebuah hari untuk bertumbuh bersama.": "A day to grow together.",
  "Dua hati, satu cerita yang tumbuh pelan menuju selamanya.": "Two hearts, one story gently growing toward forever.",
  "Galeri Botani": "Botanical Gallery",
  "Galeri Kisah": "Story Gallery",
  "Dua Hati": "Two Hearts",
  "Satu Hari": "One Day",
  "Dua hati, satu janji": "Two Hearts, One Promise",
  "Satu hari, satu selamanya": "One Day, One Forever",
  "Sebuah janji bukan hanya diucapkan, tetapi dipilih lagi pada setiap hari yang datang.": "A promise is not only spoken; it is chosen again with every day that comes.",
  "Di antara banyak tanggal, ada satu hari yang kami simpan untuk dikenang bersama.": "Among many dates, there is one day we keep to remember together.",
  "Kisah Sebelumnya": "Previous Story",
  "Kisah Berikutnya": "Next Story",
  "Tanpa foto pun, setiap detail kecil dapat menyimpan rasa dari hari yang sedang kami nantikan.": "Even without photographs, small details can hold the feeling of the day we are waiting for.",
  "Tangkai Berbunga": "A Flowering Branch",
  "Pakis Muda": "A Young Fern",
  "Ilustrasi Sebelumnya": "Previous Illustration",
  "Ilustrasi Berikutnya": "Next Illustration",
  "Dengan hati yang hangat, kami mengundang Anda untuk merayakan satu hari yang istimewa.": "With warm hearts, we invite you to celebrate a special day.",
  "Kehadiran Anda akan melengkapi kebahagiaan yang kami rawat bersama.": "Your presence will enrich the joy we have nurtured together.",
  "Semoga kasih dan kebaikan senantiasa tumbuh dalam setiap langkah yang baru.": "May love and kindness grow with every new step.",
  "Terima kasih atas doa dan kehadiran yang membuat hari ini semakin berarti. Sampai bertemu.": "Thank you for your wishes and for making this day more meaningful with your presence. We look forward to seeing you.",
  "Dengan hati yang hangat, kami mengundang Anda untuk merayakan hari ketika dua cerita memilih berjalan bersama.": "With warm hearts, we invite you to celebrate the day when two stories choose to walk together.",
  "Kehadiran Anda akan menjadi bagian hangat dari hari yang kami rayakan bersama.": "Your presence will be a warm part of the day we celebrate together.",
  "Semoga langkah baru ini selalu dipenuhi kasih, ketenangan, dan doa yang baik.": "May this new chapter be filled with love, calm, and kind wishes.",
  "Terima kasih telah hadir, mendoakan, dan menjadi bagian dari awal yang kami pilih bersama. Sampai bertemu.": "Thank you for being present, for your wishes, and for sharing in the beginning we have chosen together. We look forward to seeing you.",
  "Pernikahan Kami": "Our Wedding",
  "Hari Istimewa": "A Special Day",
  "Foto": "Photo",
  "Galeri foto": "Gallery photo",
  "Pilih Foto": "Select Photo",
  "Buka Foto": "Open Photo",
  "Tutup Foto": "Close Photo",
  "Foto Sebelumnya": "Previous Photo",
  "Foto Berikutnya": "Next Photo",
  "Atur Foto Galeri": "Edit Gallery Photos",
  "Atur Foto Sampul": "Edit Cover Photo",
  "Di antara hari-hari yang datang dan pergi, ada satu yang ingin kami rayakan bersama Anda.": "Among the days that come and go, there is one we would love to celebrate with you.",
  "Kami mengundang Anda untuk berbagi waktu, cerita, dan kebahagiaan pada hari istimewa ini.": "We invite you to share in the moments, stories, and joy of this special day.",
  "Semoga langkah baru ini selalu dikelilingi kasih, kebaikan, dan doa yang tulus.": "May this new chapter be surrounded by love, kindness, and heartfelt wishes.",
  "Terima kasih untuk setiap doa dan kehadiran yang menghangatkan hari kami. Sampai bertemu.": "Thank you for every wish and for the presence that warms our day. We look forward to seeing you.",
  "Buka Undangan": "Open Invitation",
  "Musik": "Music",
  "Musik tidak tersedia": "Music unavailable",
  "Jeda musik undangan": "Pause invitation music",
  "Putar musik undangan": "Play invitation music",
  "Jeda musik": "Pause music",
  "Putar musik": "Play music",
  "Foto belum ditambahkan.": "No photos have been added yet.",
  "Setiap foto menyimpan cerita tentang kita.": "Every photo holds a story of us.",
  "Di antara garis pensil, catatan kecil, dan benda-benda yang kami simpan, ada satu cerita yang akhirnya sampai pada hari ini.": "Between pencil lines, little notes, and the things we keep, one story has finally arrived at this day.",
  "Kami ingin menambahkan kehadiran Anda pada halaman yang paling ingin kami kenang.": "We would love to add your presence to the page we most want to remember.",
  "Semoga halaman-halaman setelah hari ini selalu penuh kasih, tawa, dan keberanian untuk terus berjalan bersama.": "May the pages after this day always hold love, laughter, and the courage to keep walking together.",
  "Terima kasih sudah berhenti sejenak di halaman ini, mendoakan, dan menjadi bagian dari cerita yang kami bawa ke bab berikutnya.": "Thank you for pausing on this page, for your wishes, and for being part of the story we carry into the next chapter.",
  "Surat kecil untukmu": "A little letter for you",
  "Jalan kecil penuh cerita": "A little path full of stories",
  "Halaman-halaman kenangan": "Pages of memories",
  "Bunga-bunga yang mekar": "Flowers in bloom",
  "Perjalanan bersama": "A journey together",
  "Lampu jalan vintage": "A vintage streetlamp",
  "Sketsa pasangan": "A sketch of us",
  "Sepeda klasik": "A classic bicycle",
  "Kamera analog": "An analog camera",
  "Kaset nostalgia": "A nostalgic cassette",
  "Balon hati": "A heart balloon",
  "Tiket kenangan": "A ticket of memories",
  "Polaroid kisah kita": "A polaroid of our story",
  "Pita merah muda": "A pink ribbon",
  "Buku-buku lama": "Old books",
  "Sebuah Undangan": "An Invitation",
  "Untuk yang terkasih": "For our dear guests",
  "Untuk momen istimewa": "For a special moment",
  "Setiap cerita punya awalnya.": "Every story has a beginning.",
  "Sebuah undangan untuk orang istimewa": "An invitation for someone special",
  "Dua hati, satu cerita yang selalu tumbuh.": "Two hearts, one ever-growing story.",
  "Dua jiwa, satu perjalanan, menuju selamanya.": "Two souls, one journey, toward forever.",
  "Hari kita berdua": "Our Special Day",
  "Hari istimewa": "A Special Day",
  "Nama belum diisi": "Name not added",
  "Setiap pertemuan menyimpan cerita yang layak dikenang.": "Every meeting holds a story worth remembering.",
  "Kenangan indah hadir dalam setiap momen yang kita rayakan bersama.": "Beautiful memories live in every moment we celebrate together.",
  "Kehadiran Anda adalah bagian dari cerita kami.": "Your presence is part of our story.",
  "Dengan hangat kami mengundang Anda untuk merayakan hari istimewa kami.": "We warmly invite you to celebrate our special day.",
  "Undangan Pernikahan": "Wedding Invitation",
  "Perayaan Pernikahan": "Wedding Celebration",
  "Mempelai": "The Couple",
  "Mempelai pertama": "First Partner",
  "Mempelai kedua": "Second Partner",
  "Sampul": "Cover",
  "Dengan Hangat": "A Warm Welcome",
  "Dengan penuh sukacita": "With Joy",
  "Yang Mengundang": "Your Hosts",
  "Detail Acara": "Event Details",
  "Tanggal & Waktu": "Date & Time",
  "Galeri Foto": "Photo Gallery",
  "Galeri Cerita": "Our Moments",
  "Menuju Hari Bahagia": "Counting Down to Our Day",
  "Menuju Hari Istimewa": "Counting Down to the Day",
  "Hitung Mundur": "Countdown",
  "Lokasi": "Location",
  "Lokasi Acara": "Event Location",
  "Konfirmasi Kehadiran": "Confirm Attendance",
  "Ucapan & Doa": "Wishes & Prayers",
  "Tanda Kasih": "Gift",
  "Kirim Hadiah": "Send a Gift",
  "Terima Kasih": "Thank You",
  "Tentang Kami": "About Us",
  "Sebuah Cerita": "A Story",
  "Hari": "Days",
  "Jam": "Hours",
  "Menit": "Minutes",
  "Detik": "Seconds",
  "Tanggal belum ditentukan": "Date not set",
  "Tanggal acara belum tersedia.": "Event date is not available yet.",
  "Lokasi belum ditentukan": "Location not set",
  "Lihat Lokasi": "View Location",
  "Buka Google Maps": "Open Google Maps",
  "Tautan lokasi belum tersedia.": "Location link is not available yet.",
  "Belum ada foto galeri.": "No gallery photos yet.",
  "Foto galeri belum ditambahkan.": "No gallery photos have been added yet.",
  "Merupakan kebahagiaan bagi kami apabila Anda berkenan hadir.": "It would mean so much to us if you could join us.",
  "Informasi tanda kasih belum ditambahkan.": "Gift details are not available yet.",
  "Salin Nomor Rekening": "Copy Account Number",
  "Salin nomor rekening": "Copy account number",
  "Nomor rekening disalin.": "Account number copied.",
  "Belum dapat menyalin. Silakan salin nomor secara manual.": "Could not copy. Please copy the number manually.",
  "Mulai": "Starts",
  "Selesai": "Ends",
  "Selesai acara": "Event ends",
  "Untuk": "For",
  "Kuota undangan": "Invitation capacity",
  "orang, termasuk penerima.": "guests, including the recipient.",
  "Nama": "Name",
  "Nama lengkap": "Full name",
  "Nama kamu": "Your name",
  "No. WhatsApp": "WhatsApp number",
  "Acara yang akan dihadiri": "Events you will attend",
  "Pilih acara": "Select an event",
  "Pilih sesi kehadiran yang aktif.": "Choose an active attendance session.",
  "Sesi ini tidak termasuk dalam undangan tamu.": "This session is not included in your invitation.",
  "Pilih sesi undangan tamu yang masih aktif.": "Choose an invited session from the active schedule.",
  "Tamu sudah check-in. Perubahan sesi RSVP perlu dibantu admin acara.": "You have checked in. Contact the event organizer to change your RSVP sessions.",
  "Upacara Nikah": "Wedding Ceremony",
  "Resepsi": "Reception",
  "Hadiri Semua Acara": "Attend All Events",
  "Status kehadiran": "Attendance status",
  "Saya Akan Hadir": "I Will Attend",
  "Saya Mungkin Hadir": "I Might Attend",
  "Saya Tidak Dapat Hadir": "I Cannot Attend",
  "Saya Tidak Hadir": "I Will Not Attend",
  "Saya Masih Tentatif": "I Am Not Sure Yet",
  "Jumlah pendamping": "Additional guests",
  "Jumlah yang hadir": "Number attending",
  "Termasuk Anda.": "Including you.",
  "orang": "guests",
  "Ya": "Yes",
  "Tidak": "No",
  "Menyimpan...": "Saving...",
  "Kirim RSVP": "Send RSVP",
  "Konfirmasi hadir berhasil.": "Attendance confirmed.",
  "Konfirmasi kehadiran tersimpan.": "Your response has been saved.",
  "RSVP belum dapat disimpan.": "Could not save your RSVP.",
  "Koneksi bermasalah. Silakan coba lagi.": "Connection issue. Please try again.",
  "Kehadiran Anda telah berhasil dikonfirmasi. Kami menantikan kehadiran Anda di hari istimewa kami.": "Your attendance is confirmed. We look forward to seeing you on our special day.",
  "Konfirmasi Anda telah tersimpan. Terima kasih telah memberi kabar bahwa Anda belum dapat hadir.": "Your response is saved. Thank you for letting us know you cannot attend.",
  "Konfirmasi Anda telah tersimpan dengan status masih tentatif.": "Your tentative response has been saved.",
  "QR check-in tamu": "Guest check-in QR",
  "Unduh QR Code": "Download QR Code",
  "Simpan QR ini dan tunjukkan kepada petugas saat tiba di acara.": "Save this QR code and show it at check-in when you arrive.",
  "RSVP Anda sudah tersimpan. QR belum tersedia; hubungi pemilik undangan untuk bantuan.": "Your RSVP is saved. The QR code is unavailable; contact the host for help.",
  "Tambah ke Kalender": "Add to Calendar",
  "Isi nama dan ucapan (nama maks. 80 karakter, ucapan maks. 600 karakter).": "Enter your name and wish (up to 80 and 600 characters respectively).",
  "Ucapan berhasil dikirim. Terima kasih!": "Your wish was sent. Thank you!",
  "Ucapan belum dapat dimuat.": "Could not load wishes.",
  "Ucapan belum dapat dikirim.": "Could not send your wish.",
  "Tulis ucapan atau doa di sini…": "Write your wish or prayer here…",
  "Kirim Ucapan": "Send Wish",
  "Mengirim…": "Sending…",
  "Memuat ucapan…": "Loading wishes…",
  "Coba Lagi": "Try Again",
  "Belum ada ucapan. Jadilah yang pertama!": "No wishes yet. Be the first!",
  "Ucapan dari tamu": "Wishes from guests",
  "Our Story belum diisi": "Our Story has not been added",
  "WITH LOVE AND GRATITUDE": "WITH LOVE AND GRATITUDE",
  "Dengan penuh sukacita, kami berbagi kabar bahagia ini bersama Anda.": "With great joy, we share this happy news with you.",
  "Sebuah cerita kecil membawa kami menuju hari yang istimewa ini.": "A little story brought us to this special day.",
  "Dengan hati yang tenang, kami berbagi satu langkah penting dalam perjalanan kami.": "With grateful hearts, we share this meaningful step in our journey.",
  "Dengan senang hati, kami mengundang Anda untuk hadir dan merayakan hari istimewa ini bersama kami.": "We would be delighted to have you celebrate this special day with us.",
  "Kami berharap Anda berkenan hadir dan menjadi bagian dari perayaan kami.": "We hope you can join us and be part of our celebration.",
  "Merupakan kebahagiaan bagi kami apabila Anda berkenan hadir pada hari istimewa ini.": "It would bring us joy to have you with us on this special day.",
  "Kehadiran Anda akan menjadi bagian berarti dari perayaan ini.": "Your presence will make this celebration even more meaningful.",
  "Semoga hari ini menjadi awal dari perjalanan yang penuh kasih dan kebaikan.": "May this day begin a journey full of love and kindness.",
  "Doa dan harapan baik Anda kami terima dengan penuh syukur.": "We are grateful for your prayers and kind wishes.",
  "Doa dan harapan baik Anda menjadi hadiah yang kami syukuri.": "Your prayers and kind wishes are a gift we cherish.",
  "Terima kasih telah menjadi bagian dari cerita kami. Sampai bertemu!": "Thank you for being part of our story. See you soon!",
  "Atas doa, restu, dan kehadiran Anda dalam perjalanan istimewa ini.": "For your prayers, blessings, and presence on this special journey.",
  "Kehadiran dan doa baik Anda berarti bagi kami. Sampai bertemu di hari bahagia!": "Your presence and kind wishes mean so much to us. See you on our special day!",
  "Kehadiran dan doa baik Anda sangat berarti. Sampai bertemu!": "Your presence and kind wishes mean so much to us. See you soon!",
  "Cinta bukan tentang menemukan seseorang yang sempurna, tetapi tentang berjalan bersama dalam ketidaksempurnaan dengan hati yang tenang.": "Love is not about finding someone perfect, but walking together through imperfection with peaceful hearts.",
};

const indonesian: Record<string, string> = {
  "A personal invitation": "Undangan personal",
  "The Celebration": "Perayaan",
  "The celebration": "Perayaan",
  "A warm welcome": "Sambutan hangat",
  "Meet the hosts": "Kenali yang mengundang",
  "Our celebration": "Perayaan kami",
  "Save the date": "Catat tanggalnya",
  "Our moments": "Momen kami",
  "The day is near": "Hari istimewa kian dekat",
  "Your presence matters": "Kehadiran Anda berarti",
  "Kind words": "Ucapan penuh makna",
  "Until we meet": "Sampai bertemu",
  "Forever begins here": "Selamanya dimulai di sini",
  "Selected events": "Rangkaian acara",
  "In full bloom": "Mekar bersama",
  "A gilded celebration": "Perayaan berkilau",
  "Handcrafted in paper": "Dibuat dengan sepenuh hati",
  "Written in the stars": "Tertulis di bintang",
  "Every little moment matters.": "Setiap momen kecil berarti.",
  "A LITTLE STORY OF US": "SEBUAH CERITA TENTANG KAMI",
  "THE WEDDING OF": "PERNIKAHAN",
  "The Wedding Of": "Pernikahan",
  "The wedding invitation": "Undangan pernikahan",
  "The wedding of": "Pernikahan",
  "The two of us": "Kisah berdua",
  "A warm invitation": "Undangan hangat",
  "A day to remember": "Hari yang berkesan",
  "Our memories": "Kenangan kami",
  "Counting the moments": "Menghitung hari",
  "Find your way": "Temukan lokasinya",
  "Your presence means so much": "Kehadiran Anda berarti",
  "A little note of love": "Sepatah kata penuh kasih",
  "With gratitude": "Dengan rasa syukur",
  "Our Story": "Cerita kami",
};

export function invitationText(language: InvitationLanguage, text: string) {
  return language === "EN" ? english[text] ?? text : indonesian[text] ?? text;
}

export function localizedWeddingParentLine(language: InvitationLanguage, fatherName?: string | null, motherName?: string | null, childOrder?: number | null, kind: WeddingChildKind = "anak", position?: string | null) {
  if (language !== "EN") return weddingParentLine(fatherName, motherName, childOrder, kind, position);
  const parents = [fatherName?.trim() ? `Mr ${invitationTitleCase(fatherName.trim())}` : "", motherName?.trim() ? `Mrs ${invitationTitleCase(motherName.trim())}` : ""].filter(Boolean);
  if (!parents.length) return "";
  const order = position === "ELDEST" ? "eldest" : position === "YOUNGEST" ? "youngest" : childOrder && childOrder > 0 ? (() => {
    const suffix = childOrder % 100 >= 11 && childOrder % 100 <= 13 ? "th" : ({ 1: "st", 2: "nd", 3: "rd" } as Record<number, string>)[childOrder % 10] ?? "th";
    return `${childOrder}${suffix}`;
  })() : "";
  const child = kind === "putra" ? "Son" : kind === "putri" ? "Daughter" : "Child";
  return `${order ? `${invitationTitleCase(order)} ` : ""}${child} of ${parents.join(" & ")}`;
}

/** Translate only built-in defaults; preserve every customer edit and event description verbatim. */
export function localizedEditableCopy(designKey: string, templateKey: string, description: string | null | undefined, language: InvitationLanguage): EditableInvitationCopy {
  const defaults = invitationCopyDefaults(templateKey, description);
  const edits = parseEditableCopy(designKey);
  const copy = { ...defaults, ...edits };
  if (language !== "EN") return copy;
  const standardDefaults = invitationCopyDefaults(templateKey);
  for (const field of Object.keys(copy) as (keyof EditableInvitationCopy)[]) {
    if (copy[field] === standardDefaults[field] && copy[field]) copy[field] = invitationText(language, copy[field]);
  }
  return { ...copy, ...parseEnglishEditableCopy(designKey) };
}
