export const invitationPalettes = {
  blossom: { name: "Eternal Blossom", bg: "#f7edea", surface: "#fff9f3", ink: "#673f4d", accent: "#99566b", soft: "#dfb8bd" },
  botanical: { name: "Botanical Ivory", bg: "#f6f1e7", surface: "#fffaf1", ink: "#38342d", accent: "#6f725d", soft: "#c8c1ad" },
  serein: { name: "Serein", bg: "#f4eee5", surface: "#fcf8f1", ink: "#442936", accent: "#442936", soft: "#cab6a2" },
  rose: { name: "Rose", bg: "#fbf2f0", surface: "#fffaf8", ink: "#2d2020", accent: "#7a1c25", soft: "#e8b7b1" },
  blush: { name: "Blush", bg: "#fff4f6", surface: "#fffafb", ink: "#34242a", accent: "#a44f62", soft: "#e9a9b9" },
  paperMeadow: { name: "Paper Cut Botanical", bg: "#eee8d8", surface: "#fffaf0", ink: "#344139", accent: "#72835f", soft: "#d4c8ad" },
  sage: { name: "Sage", bg: "#f3f5ee", surface: "#fcfcf8", ink: "#273027", accent: "#65775f", soft: "#b8c9ae" },
  gardenGlow: { name: "Garden Light", bg: "#eef0df", surface: "#fff9ec", ink: "#334437", accent: "#9a7746", soft: "#c7d1a8" },
  pencil: { name: "Pencil Reverie", bg: "#f2e9dd", surface: "#fffaf2", ink: "#302c2a", accent: "#b96f7e", soft: "#d4bfb3" },
  zen: { name: "Zen Atelier", bg: "#f4f0e6", surface: "#fbf8f0", ink: "#373c34", accent: "#a9513b", soft: "#c9bda9" },
  night: { name: "Night", bg: "#171318", surface: "#211b22", ink: "#f8f2ee", accent: "#e7a9b1", soft: "#9b7079" },
  celestialIndigo: { name: "Celestial Ink", bg: "#07111f", surface: "#10243a", ink: "#eaf2f7", accent: "#b8d9e9", soft: "#63789a" },
  pearl: { name: "Pearl", bg: "#f5f1ea", surface: "#fffdf8", ink: "#292522", accent: "#806a5a", soft: "#cdbba8" },
  pearlAtelier: { name: "Classic Pearl", bg: "#f3efe6", surface: "#fffdf8", ink: "#322c28", accent: "#a18458", soft: "#d8cbbb" },
  terracotta: { name: "Terracotta", bg: "#f8eee8", surface: "#fff8f3", ink: "#38251f", accent: "#a9553f", soft: "#d9a28f" },
  olive: { name: "Olive", bg: "#f1f2e8", surface: "#fbfcf5", ink: "#292c22", accent: "#69734d", soft: "#b9c29b" },
  champagne: { name: "Champagne", bg: "#f6f0df", surface: "#fffaf0", ink: "#30291f", accent: "#a27b45", soft: "#d8c39b" },
  mauve: { name: "Mauve", bg: "#f4edf2", surface: "#fcf7fb", ink: "#30252e", accent: "#8c607d", soft: "#c9a5ba" },
  ocean: { name: "Ocean", bg: "#edf4f5", surface: "#f9fcfc", ink: "#1f2d30", accent: "#39737a", soft: "#a6cdd0" },
  plum: { name: "Plum", bg: "#f3edf4", surface: "#fbf7fc", ink: "#2e202f", accent: "#70456f", soft: "#b997b8" },
  monochrome: { name: "Monochrome", bg: "#f4f3f1", surface: "#ffffff", ink: "#202020", accent: "#3d3d3d", soft: "#bdbdbd" },
  maroon: { name: "Maroon", bg: "#4a111b", surface: "#fff7f2", ink: "#3a1118", accent: "#7b1f2b", soft: "#d5a59b" },
  midnight: { name: "Midnight", bg: "#11131a", surface: "#f9f4ee", ink: "#141720", accent: "#8f7b9d", soft: "#c5b9cb" },
  midnightVelvet: { name: "Midnight Romance", bg: "#080b18", surface: "#12182b", ink: "#f3e8d8", accent: "#b58a56", soft: "#642b43" },
  decoNoir: { name: "Golden Art Deco", bg: "#0d0f0c", surface: "#171a14", ink: "#f3e7c8", accent: "#c79a45", soft: "#6d552e" },
  velvetHorizon: { name: "Velvet Horizon", bg: "#f1e4d7", surface: "#fff7ed", ink: "#4a302a", accent: "#9a5147", soft: "#c8a89a" },
  littleCloud: { name: "Little Cloud", bg: "#eff5f5", surface: "#fffaf2", ink: "#24464b", accent: "#366b72", soft: "#e4b89a" },
  gathering: { name: "Gathering", bg: "#f8f2e6", surface: "#fffcf5", ink: "#26372e", accent: "#315b45", soft: "#df9c70" },
  silverReverie: { name: "Silver Reverie", bg: "#eef1f2", surface: "#fbfaf7", ink: "#263a48", accent: "#536b7a", soft: "#b5c4cd" },
  goldenKeepsake: { name: "Golden Keepsake", bg: "#f4e7ce", surface: "#fffaf0", ink: "#51341c", accent: "#8c5e1a", soft: "#d7b67b" },
  confetti: { name: "Confetti Club", bg: "#fff6e5", surface: "#fffcf5", ink: "#222c51", accent: "#2445ae", soft: "#f77959" },
  cherryPicnic: { name: "Cherry Picnic", bg: "#fff4e6", surface: "#fffaf1", ink: "#652b32", accent: "#a32e42", soft: "#e2baa7" },
  velvetWish: { name: "Velvet Wish", bg: "#291721", surface: "#fff0df", ink: "#fff0df", accent: "#d7b275", soft: "#5c3447" },
  littleParade: { name: "Little Parade", bg: "#fff6df", surface: "#eff1df", ink: "#344b3e", accent: "#a84d35", soft: "#c8d3af" },
  discoBloom: { name: "Disco Bloom", bg: "#f8dfd5", surface: "#fff4e9", ink: "#592c3b", accent: "#963f59", soft: "#d7a9ac" },
  tamanDoa: { name: "Prayer Garden", bg: "#f7f1e4", surface: "#eef1e5", ink: "#284332", accent: "#315c45", soft: "#d9cfb4" },
  redThread: { name: "Red Thread", bg: "#7c242d", surface: "#fff3da", ink: "#fff3da", accent: "#d8af69", soft: "#b84f4a" },
  serambiPagi: { name: "Morning Courtyard", bg: "#f5f0e5", surface: "#fcf8ee", ink: "#304637", accent: "#45603f", soft: "#d3c4a4" },
  rumahSenja: { name: "Twilight Home", bg: "#f3e6d6", surface: "#fff8ed", ink: "#563726", accent: "#874f37", soft: "#cfa680" },
  langitSafari: { name: "Safari Skies", bg: "#f5efdf", surface: "#eef1e5", ink: "#36472f", accent: "#46623b", soft: "#d7b98f" },
  purnamaBiru: { name: "Blue Moon", bg: "#101f35", surface: "#f8efdf", ink: "#f8efdf", accent: "#d1b27f", soft: "#304765" },
  giokAbadi: { name: "Eternal Jade", bg: "#e8ede4", surface: "#f9f5e8", ink: "#284438", accent: "#36594d", soft: "#b5c5a9" },
  peonySilk: { name: "Peony Silk", bg: "#f2e3dc", surface: "#fff7ec", ink: "#643947", accent: "#8a4a60", soft: "#d8b2ba" },
  imperialCrimson: { name: "Imperial Crimson", bg: "#4a0d15", surface: "#fff0d4", ink: "#fff0d4", accent: "#dfb873", soft: "#8e3036" },
  porcelainBloom: { name: "Porcelain Bloom", bg: "#f5f2e8", surface: "#fffcf5", ink: "#203b63", accent: "#2a4e80", soft: "#b6c6d6" },
} as const;

export const invitationFonts = {
  abrilLato: { name: "Abril Fatface + Lato", heading: "Abril Fatface", body: "Lato" },
  arimaMulish: { name: "Arima Madurai + Mulish", heading: "Arima Madurai", body: "Mulish" },
  arvoLato: { name: "Arvo + Lato", heading: "Arvo", body: "Lato" },
  archivoTenor: { name: "Archivo Narrow + Tenor Sans", heading: "Archivo Narrow", body: "Tenor Sans" },
  bubblegumOpenSans: { name: "Bubblegum Sans + Open Sans", heading: "Bubblegum Sans", body: "Open Sans" },
  cardoHind: { name: "Cardo + Hind", heading: "Cardo", body: "Hind" },
  chonburiDomine: { name: "Chonburi + Domine", heading: "Chonburi", body: "Domine" },
  cinzelFauna: { name: "Cinzel + Fauna One", heading: "Cinzel", body: "Fauna One" },
  crimsonDmSans: { name: "Crimson Pro + DM Sans", heading: "Crimson Pro", body: "DM Sans" },
  dotGothicSpace: { name: "DotGothic16 + Space Mono", heading: "DotGothic16", body: "Space Mono" },
  fjallaCantarell: { name: "Fjalla One + Cantarell", heading: "Fjalla One", body: "Cantarell" },
  fugazWork: { name: "Fugaz One + Work Sans", heading: "Fugaz One", body: "Work Sans" },
  grandLato: { name: "Grand Hotel + Lato", heading: "Grand Hotel", body: "Lato" },
  instrumentGeist: { name: "Instrument Sans + Geist", heading: "Instrument Sans", body: "Geist" },
  interKrub: { name: "Inter + Krub", heading: "Inter", body: "Krub" },
  montserratKarla: { name: "Montserrat + Karla", heading: "Montserrat", body: "Karla" },
  nunitoLora: { name: "Nunito + Lora", heading: "Nunito", body: "Lora" },
  nunitoPtSans: { name: "Nunito + PT Sans", heading: "Nunito", body: "PT Sans" },
  oswaldSourceSerif: { name: "Oswald + Source Serif 4", heading: "Oswald", body: "Source Serif 4" },
  philosopherMulish: { name: "Philosopher + Mulish", heading: "Philosopher", body: "Mulish" },
  playfairLato: { name: "Playfair Display + Lato", heading: "Playfair Display", body: "Lato" },
  playfairLora: { name: "Playfair Display + Lora", heading: "Playfair Display", body: "Lora" },
  playfairQuicksand: { name: "Playfair Display + Quicksand", heading: "Playfair Display", body: "Quicksand" },
  playfairInter: { name: "Playfair Display + Inter", heading: "Playfair Display", body: "Inter" },
  poiretMontserrat: { name: "Poiret One + Montserrat", heading: "Poiret One", body: "Montserrat" },
  quicksand: { name: "Quicksand", heading: "Quicksand", body: "Quicksand" },
  ralewayMerriweather: { name: "Raleway + Merriweather", heading: "Raleway", body: "Merriweather" },
  rethinkSpectral: { name: "Rethink Sans + Spectral", heading: "Rethink Sans", body: "Spectral" },
  robotoLora: { name: "Roboto + Lora", heading: "Roboto", body: "Lora" },
  rufinaAverage: { name: "Rufina + Average Sans", heading: "Rufina", body: "Average Sans" },
  sacramentoAlice: { name: "Sacramento + Alice", heading: "Sacramento", body: "Alice" },
  sintonyPoppins: { name: "Sintony + Poppins", heading: "Sintony", body: "Poppins" },
  spaceJakarta: { name: "Space Mono + Plus Jakarta Sans", heading: "Space Mono", body: "Plus Jakarta Sans" },
  stintPontano: { name: "Stint Ultra Expanded + Pontano Sans", heading: "Stint Ultra Expanded", body: "Pontano Sans" },
  sourceSansAlegreya: { name: "Source Sans 3 + Alegreya", heading: "Source Sans 3", body: "Alegreya" },
  syneInter: { name: "Syne + Inter", heading: "Syne", body: "Inter" },
  ultraSlabo: { name: "Ultra + Slabo 27px", heading: "Ultra", body: "Slabo 27px" },
  ubuntuRokkitt: { name: "Ubuntu + Rokkitt", heading: "Ubuntu", body: "Rokkitt" },
  yellowtailRethink: { name: "Yellowtail + Rethink Sans", heading: "Yellowtail", body: "Rethink Sans" },
  yesevaJosefin: { name: "Yeseva One + Josefin Sans", heading: "Yeseva One", body: "Josefin Sans" },
  youngInstrument: { name: "Young Serif + Instrument Sans", heading: "Young Serif", body: "Instrument Sans" },
  bodoniManrope: { name: "Bodoni Moda + Manrope", heading: "Bodoni Moda", body: "Manrope" },
  cormorantManrope: { name: "Cormorant Garamond + Manrope", heading: "Cormorant Garamond", body: "Manrope" },
} as const;

export type PaletteKey = keyof typeof invitationPalettes;
export type FontKey = keyof typeof invitationFonts;

export function makeDesignKey(template: string, palette: PaletteKey, font: FontKey, decor?: string) {
  const base = `${template}::${palette}::${font}`;
  return decor ? `${base}::decor=${encodeURIComponent(decor)}` : base;
}

export function parseDesignKey(key: string) {
  const [template = "eternal-blossom", palette = "rose", font = "cinzelFauna", ...parts] = key.split("::");
  const decorPart = parts.find((part) => part.startsWith("decor="));
  return {
    template,
    palette: (palette in invitationPalettes ? palette : "rose") as PaletteKey,
    font: (font in invitationFonts ? font : "cinzelFauna") as FontKey,
    decor: decorPart ? decodeURIComponent(decorPart.slice("decor=".length)) : null,
  };
}
